### ISSUE TITLE
Remote Server Returns error ( 403 Forbidden ) 

### ISSUE THREAD

**Issue by Cyb3rN3rd777** [ricardojoserf/SharpCovertTube#1]
Hello,

first off, thank you for sharing this tool, very cool idea that you have!

Although i noticed i have an issue when i try to execute the tool, seems like it cant get the listener to start :

<img width="721" alt="Screenshot 2024-06-14 at 11 50 35 AM" src="https://github.com/ricardojoserf/SharpCovertTube/assets/144471817/1d1e0eea-999c-4dc4-9134-6da801b5bc19">

( i made sure my firewall is desactivated + executed it with Admin rights ) 

but that doesn't seem to be the problem. 

Do you know what the issue might be ? 

Thanks,

**Comment by ricardojoserf** [comment]
Hi @Cyb3rN3rd777, you are welcome I am happy you like it! 
This is weird, I never got a 403 error code before. Your channel ID looks ok, in my case the channel id is 24 characters long and the API key is 39 characters (I just recompiled the tool and everything works from my side). 
If that does not solve it, maybe before using the tool your IP address got banned for any other reason, so maybe you could try using a VPN?
Regards,
Ricardo

**Comment by Cyb3rN3rd777** [comment]
Alright 
Thanks, ill try that out!

**Comment by ricardojoserf** [comment]
Hi I have been doing some tests last days while developing the c2-server script which automates generating and uploading videos to Youtube and receiving and decoding the DNS queries. I got the 403 error only when the quota was reached so I got the problem because I was doing too many requests to Google API, so my recommendation for this is to set the time between requests to 10 minutes or more.
